# LLM Models Configuration
model_families:
  gemini:
    description: "Google Gemini Models"
    models:
      gemini20:
        name: "gemini-2.0-pro-exp-02-05"
        input_cost: 0.00025
        output_cost: 0.0005
        description: "Gemini 2.0 Pro"
      gemini20flash:
        name: "gemini-2.0-flash"
        input_cost: 0.00015
        output_cost: 0.0006
        description: "Gemini 2.0 Flash"
      gemini15:
        name: "gemini-1.5-pro"
        input_cost: 0.00125
        output_cost: 0.005
        description: "Gemini 1.5 Pro"
      vision:
        name: "gemini-pro-vision"
        input_cost: 0.00025
        output_cost: 0.0005
        description: "Gemini Pro Vision"

  openai:
    description: "OpenAI Models"
    models:
      gpt3:
        name: "gpt-3.5-turbo"
        input_cost: 0.0005
        output_cost: 0.0015
        description: "GPT-3.5 Turbo"
      gpt4:
        name: "gpt-4-turbo-preview"
        input_cost: 0.01
        output_cost: 0.03
        description: "GPT-4 Turbo"

  deepseek:
    description: "DeepSeek Models"
    base_url: "https://api.deepseek.com/v1"
    models:
      chat:
        name: "deepseek-chat"
        input_cost: 0.0002
        output_cost: 0.0002
        description: "DeepSeek Chat"
      reasoner:
        name: "deepseek-reasoner"
        input_cost: 0.0003
        output_cost: 0.0003
        description: "DeepSeek Reasoner"

  groq:
    description: "Groq Models"
    models:
      deepseek:
        name: "deepseek-r1-distill-llama-70b"
        input_cost: 0.0005
        output_cost: 0.0005
        description: "DeepSeek on Groq"
        
  anthropic:
    description: "Anthropic Claude Models"
    models:
      sonnet:
        name: "claude-3-sonnet-20240229"
        input_cost: 0.0015
        output_cost: 0.0015
        description: "Claude 3 Sonnet"
      haiku:
        name: "claude-3-haiku-20240307"
        input_cost: 0.00025
        output_cost: 0.00125
        description: "Claude 3 Haiku"

  mistral:
    description: "Mistral AI Models"
    models:
      medium:
        name: "mistral-medium"
        input_cost: 0.0003
        output_cost: 0.0003
        description: "Mistral Medium"

  

# Prompts Configuration
prompts:
  chat:
    system_message: |
      You are an AI assistant. Always be direct and clear in your responses.
  search:
    response_format: |
      Please provide your response in the following format:

      1. First, under a '## Key Takeaways' heading, provide a concise summary of the main points and key findings.
      2. Then, provide a comprehensive analysis of the search results, citing sources when appropriate.

      Make sure the summary is clear and actionable, followed by a thorough and accurate analysis of all sources.